### ISSUE TITLE
Como saber se o voto computou

### ISSUE THREAD

**Issue by bgabraga2** [izmcm/BBBot#11]
Rapaziada como confirmar se meu voto funcionou? Rola colocar um contador de votos que funcionaram?

**Comment by cleivson** [comment]
O problema é que o bot loga muita coisa, então não sei se tem um momento adequado pra mostrar quantos votos foram. Mas sempre que vai com sucesso ele loga "Voto com sucesso".

**Comment by bgabraga2** [comment]
ahh então aqui não está rodando direito... não recebi nenhum "Voto com sucesso" até agora kkkk. Ele entra no loading do captcha e reload pro primeiro passo do voto...

**Comment by MiniMarvin** [comment]
@bgabraga2 na nova versão ele já diz quantos votos válidos estão sendo enviados, corrigimos isso a pouco tempo, vou melhorar o log para os usuários, como ainda estava tendo muito debug deixamos os  prints, mas vou limpar o debug do bot

**Comment by joaomwill** [comment]
@MiniMarvin Fala ai mano boa noite, nao entendi mt bem como faz pra instalar, ja instalei os programas , se importa de me dar uma ajuda?

**Comment by MiniMarvin** [comment]
@joaomwill abre uma issue com tua dúvida certinho, tipo:
- fiz passos a b c, mas não consigo fazer o passo d
pra que eu possa te ajudar melhor

**Comment by bgabraga2** [comment]
Parece que esta nova versão está redondinha com os logs @MiniMarvin Valeu!
