### ISSUE TITLE
Carregando infinitamente o voto

### ISSUE THREAD

**Issue by zardLopes** [izmcm/BBBot#14]
Dps que valida o captcha ele fica carregando infinitamente a votação

**Comment by zardLopes** [comment]
Processando infinitamente

**Comment by linkgab** [comment]
A frase Processando seu voto não faz parte da programação. Se você tentar votar manualmente também está tendo esse problema.

**Comment by MiniMarvin** [comment]
nesse caso o problema é basicamente da globo que não está suportando bem o número de acessos que está tendo hoje, por isso estarei fechando a issue
