### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by GuilhermeTiede** [izmcm/BBBot#15]
C:\Users\USER\AppData\Local\Programs\Python\Python37\Lib\site-packages\selenium\webdriver\firefox\firefox_profile.py:208: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if setting is None or setting is '':
Traceback (most recent call last):
  File "script.py", line 7, in <module>
    import processing
  File "C:\Users\USER\Desktop\BBBOT2\BBBot\processing.py", line 1, in <module>
    import cv2
  File "C:\Users\USER\AppData\Local\Programs\Python\Python37\Lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ModuleNotFoundError: No module named 'cv2.cv2'

Ja instalei o opencv, tentei com o conda também mas nao funciona por nada

**Comment by MiniMarvin** [comment]
Pelo que parece você está utilizando uma versão do python que não dá suporte ao opencv ainda, tenta utilizar um environment com o python 3.6 como no exemplo de criação do environment com o conda:
```conda create --name opencv-env python=3.6```

**Comment by phensalves** [comment]
@MiniMarvin aqui no Mojave e Firefox 74.0 não compouta o voto no final, dá "Ocorreu um erro"...
