### ISSUE TITLE
Erro ao Iniciar #from selenium import webdriver ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by fabotse** [izmcm/BBBot#16]
Esta dando esse erro depois de instalar as dependencias e iniciar:

 from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

**Comment by MiniMarvin** [comment]
esse erro significa que o selenium não foi instalado corretamente, recomendo tentar instalar novamente o selenium e tentar novamente
