### ISSUE TITLE
``list index out of range``

### ISSUE THREAD

**Issue by victorpd96** [izmcm/BBBot#25]
toda vez antes de dar as opçoes de voto, alguem ajuda?

**Comment by victorpd96** [comment]
Traceback (most recent call last):
  File "C:\Users\Victor\Desktop\BBBot-1-master\script.py", line 62, in <module>
    option = input("quem você quer eliminar?: \n 1. "+names[0]+"\n 2. "+names[1]+"\n 3. "+names[2]+"\ndigite o número da pessoa: ")
IndexError: list index out of range

**Comment by izmcm** [comment]
Opa! Consertado no commit cd3f9ce46ea663f72cb49f1fc186581cdf1586c5
