### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rwintrich** [izmcm/BBBot#6]
Não que eu tenha tentado usar isso para alguma finalidade não educacional, porem =/ ta com erro no metodo perfom.
 ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()

**Comment by dezordi** [comment]
esse erro está levando a selecionar sempre o mesmo captcha?

**Comment by phernandp** [comment]
Apresentou novo erro.

iniciando o bot
Paredão BBB20: Quem você quer eliminar? Felipe, Manu ou Mari?
 Felipe, Manu ou Mari
Manu é o botao 1
procurando por pia
salvando
a imagem se encontra nos pontos: 92.0 X 35.0
o tamanho do captcha é 269.0 X 57.0
Traceback (most recent call last):
  File "script.py", line 111, in <module>
    ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
  File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
    self.w3c_actions.perform()
  File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
    self.driver.execute(Command.W3C_ACTIONS, enc)
  File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (634, 905) is out of bounds of viewport width (1280) and height (873)

**Comment by dezordi** [comment]
> Apresentou novo erro.
> 
> iniciando o bot
> Paredão BBB20: Quem você quer eliminar? Felipe, Manu ou Mari?
> Felipe, Manu ou Mari
> Manu é o botao 1
> procurando por pia
> salvando
> a imagem se encontra nos pontos: 92.0 X 35.0
> o tamanho do captcha é 269.0 X 57.0
> Traceback (most recent call last):
> File "script.py", line 111, in
> ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
> File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
> self.w3c_actions.perform()
> File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
> self.driver.execute(Command.W3C_ACTIONS, enc)
> File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (634, 905) is out of bounds of viewport width (1280) and height (873)

só funciona pra votar no prior, abraço.

**Comment by meltedgod** [comment]
> só funciona pra votar no prior, abraço.

kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

**Comment by phernandp** [comment]
> > Apresentou novo erro.
> > 
> > iniciando o bot
> > Paredão BBB20: Quem você quer eliminar? Felipe, Manu ou Mari?
> > Felipe, Manu ou Mari
> > Manu é o botao 1
> > procurando por pia
> > salvando
> > a imagem se encontra nos pontos: 92.0 X 35.0
> > o tamanho do captcha é 269.0 X 57.0
> > Traceback (most recent call last):
> > File "script.py", line 111, in
> > ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
> > self.w3c_actions.perform()
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
> > self.driver.execute(Command.W3C_ACTIONS, enc)
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (634, 905) is out of bounds of viewport width (1280) and height (873)
> 
> só funciona pra votar no prior, abraço.

Ata. Quer um biscoito?

**Comment by phernandp** [comment]
> > Apresentou novo erro.
> > 
> > iniciando o bot
> > Paredão BBB20: Quem você quer eliminar? Felipe, Manu ou Mari?
> > Felipe, Manu ou Mari
> > Manu é o botao 1
> > procurando por pia
> > salvando
> > a imagem se encontra nos pontos: 92.0 X 35.0
> > o tamanho do captcha é 269.0 X 57.0
> > Traceback (most recent call last):
> > File "script.py", line 111, in
> > ac.move_to_element(captcha).move_by_offset(posX, posY).click().perform()
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform
> > self.w3c_actions.perform()
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform
> > self.driver.execute(Command.W3C_ACTIONS, enc)
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "/home/pheno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (634, 905) is out of bounds of viewport width (1280) and height (873)
> 
> só funciona pra votar no prior, abraço.

Já arrumei. Hehe
