### ISSUE TITLE
Erro ao iniciar o script

### ISSUE THREAD

**Issue by bgabraga2** [izmcm/BBBot#9]
Olá! 

Estou tentando rodar o bot mas estou tendo o seguinte problema

```
Traceback (most recent call last):
  File "script.py", line 29, in <module>
    browser = webdriver.Firefox(capabilities=caps)
  File "/home/bruno/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/home/bruno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/bruno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/bruno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/bruno/.local/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: invalid argument: can't kill an exited process
```

Segui todos os passos mas ainda sem sucesso. Estou rodando no linux Mint. 

Alguém com o mesmo problema ou que pode me auxiliar?

**Comment by rammonfelip** [comment]
Estou com um problema parecido, também uso o Linux Mint.

> Traceback (most recent call last):
>   File "script.py", line 24, in <module>
>     browser = webdriver.Chrome(capabilities=caps)
> TypeError: __init__() got an unexpected keyword argument 'capabilities'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "script.py", line 29, in <module>
>     browser = webdriver.Firefox(capabilities=caps)
>   File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
>     self.service.start()
>   File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
>     stdin=PIPE)
>   File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
>   File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> OSError: [Errno 8] Exec format error: 'geckodriver'

**Comment by bgabraga2** [comment]
Que estranho. Isso tá me parecendo algo relacionado na hora do import ***DesiredCapabilities***

**Comment by bgabraga2** [comment]
Consegui resolver. Na linha onde ele atribui as capabilities, precisa colocar um .copy ao final, tanto do Chrome quanto do Firefox

```
caps = DesiredCapabilities().CHROME.copy()
```
e 

```
caps = DesiredCapabilities().FIREFOX.copy()
```

Veja se rola!

**Comment by cleivson** [comment]
> Estou com um problema parecido, também uso o Linux Mint.
> 
> > Traceback (most recent call last):
> > File "script.py", line 24, in 
> > browser = webdriver.Chrome(capabilities=caps)
> > TypeError: **init**() got an unexpected keyword argument 'capabilities'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "script.py", line 29, in 
> > browser = webdriver.Firefox(capabilities=caps)
> > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in **init**
> > self.service.start()
> > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
> > stdin=PIPE)
> > File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> > restore_signals, start_new_session)
> > File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > OSError: [Errno 8] Exec format error: 'geckodriver'

@rammonfelip  Esse problema de geckodriver aconteceu comigo quando estava usando a versão do driver que não é pro meu OS. Vai lá página de releases e e confirma se você está com a versão pro linux.

**Comment by bgabraga2** [comment]
> > Estou com um problema parecido, também uso o Linux Mint.
> > > Traceback (most recent call last):
> > > File "script.py", line 24, in
> > > browser = webdriver.Chrome(capabilities=caps)
> > > TypeError: **init**() got an unexpected keyword argument 'capabilities'
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last):
> > > File "script.py", line 29, in
> > > browser = webdriver.Firefox(capabilities=caps)
> > > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in **init**
> > > self.service.start()
> > > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
> > > stdin=PIPE)
> > > File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> > > restore_signals, start_new_session)
> > > File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> > > raise child_exception_type(errno_num, err_msg, err_filename)
> > > OSError: [Errno 8] Exec format error: 'geckodriver'
> 
> @rammonfelip Esse problema de geckodriver aconteceu comigo quando estava usando a versão do driver que não é pro meu OS. Vai lá página de releases e e confirma se você está com a versão pro linux.

Então, no inicio eu estava com o problema que o geckodriver não era do meu OS, mas depois corrigi e deu esse problema também... mas resolveu colocando o ***.copy()*** no final na hora de atribuir a capabilitie

**Comment by rammonfelip** [comment]
> > Estou com um problema parecido, também uso o Linux Mint.
> > > Traceback (most recent call last):
> > > File "script.py", line 24, in
> > > browser = webdriver.Chrome(capabilities=caps)
> > > TypeError: **init**() got an unexpected keyword argument 'capabilities'
> > > During handling of the above exception, another exception occurred:
> > > Traceback (most recent call last):
> > > File "script.py", line 29, in
> > > browser = webdriver.Firefox(capabilities=caps)
> > > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in **init**
> > > self.service.start()
> > > File "/home/feliperamon/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
> > > stdin=PIPE)
> > > File "/usr/lib/python3.6/subprocess.py", line 729, in **init**
> > > restore_signals, start_new_session)
> > > File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
> > > raise child_exception_type(errno_num, err_msg, err_filename)
> > > OSError: [Errno 8] Exec format error: 'geckodriver'
> 
> @rammonfelip Esse problema de geckodriver aconteceu comigo quando estava usando a versão do driver que não é pro meu OS. Vai lá página de releases e e confirma se você está com a versão pro linux.

Deu certo aqui man.. não tinha checado o release! Valeu!!

**Comment by rammonfelip** [comment]
> Consegui resolver. Na linha onde ele atribui as capabilities, precisa colocar um .copy ao final, tanto do Chrome quanto do Firefox
> 
> ```
> caps = DesiredCapabilities().CHROME.copy()
> ```
> 
> e
> 
> ```
> caps = DesiredCapabilities().FIREFOX.copy()
> ```
> 
> Veja se rola!

Deu certo também, não sei se era isso ou o release hehe fiz os dois juntos.

Testando aqui a implementação

**Comment by MiniMarvin** [comment]
corrigido na master
